version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: library_management
    container_name: library_management
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "npm run start:dev"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
